name: "Redispatch PyTorch events"

on:
  repository_dispatch:
    types: [pytorch-pr-event]

jobs:
  redispatch-pr-event:
    name: "Redispatch PR event - #${{ github.event.client_payload.pull_request.number }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print PR event payload
        continue-on-error: true
        run: |
          printf "payload: ${{ toJSON(github.event.client_payload) }}"

      - name: Redispatch PR event
        uses: peter-evans/repository-dispatch@v3
        with:
          # token: ${{ secrets.COSDT_BOT_TOKEN }}
          repository: ${{ github.repository }}
          event-type: pytorch-pr-event-redispatch
          client-payload: ${{ toJSON(github.event.client_payload) }}
